name: Build, Test, Dockerize, Deploy Locally

on:
  push:
    branches:
      - main

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Build Docker Image
        run: docker build -t yourapp:latest .

      - name: Run Docker Container
        run: |
          docker stop yourapp || true
          docker rm yourapp || true
          docker run -d -p 5000:80 --name yourapp yourapp:latest

      - name: Verify container is running
        run: docker ps -a