name: Build, Test, Dockerize, Deploy Locally

on:
  push:
    branches:
      - main

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
        dotnet-version: '9.0.100-preview.2' # Use the correct available preview version


      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test --no-build --verbosity normal

      - name: Build Docker image
        run: docker build -t sampleforaws:latest .

      - name: Run Docker container
        run: |
          docker stop sampleforaws || true
          docker rm sampleforaws || true
          docker run -d -p 5000:80 --name sampleforaws sampleforaws:latest

      - name: Verify container is running
        run: docker ps -a
